import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ProvidersComponent from "@/components/ProvidersComponents/ProvidersComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShopMart",
  description: "Generated by create next app",
    icons: {
    icon: "https://cdn-icons-png.flaticon.com/512/1413/1413908.png",
    shortcut: "https://cdn-icons-png.flaticon.com/512/1413/1413908.png",
    apple: "https://cdn-icons-png.flaticon.com/512/1413/1413908.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProvidersComponent>
          {children}
        </ProvidersComponent>
          <Toaster richColors />
      </body>
    </html>
  );
}
